### ISSUE TITLE
digispark usage

### ISSUE THREAD

**Issue by beckmx** [sowbug/usb-led#55]
I bought a digispark to test this firmware, from what I saw, it's the same chip, and contains the micronucleus already installed, but when I tried using it, it says the produced firmware is 400 bytes longer, or are there pieces of code not needed?

**Comment by sowbug** [comment]
That's interesting! I am sure you'll be able to get it to work on a
Digispark after a little tinkering. I don't know which firmware you're
talking about or what "it" refers to (Digispark? Micronucleus?), but I'm
going to guess that you're talking about the micronucleus command-line tool
saying that the to-be-uploaded firmware is too big. That might mean that
the copy of the micronucleus bootloader on the Digispark is too big, which
means that there isn't enough room left for the weblight firmware.

It's been a while since I worked on this part of the project, but according
to https://github.com/sowbug/weblight/tree/master/firmware/hex it looks
like I built a custom version of the micronucleus bootloader, and you can
see from
https://github.com/sowbug/weblight/blob/master/firmware/Makefile#L25 which
version is built into WebLight.

So if that's the reason for the difference in size, then you need to figure
out how to update micronucleus on the digispark to a smaller version so
that it can fit all of the weblight firmware. Or else remove parts of
weblight, which will probably be a lot of work for you because you can't
debug until you've removed a large part of it. I'd remove the sequencer
first, though some parts of it are unfortunately necessary.

Good luck.

**Comment by beckmx** [comment]
so, from what I read and saw, the approach initially taken has been deprecated from chrome, now some interfaces are no longer useful :( I noticed actually that you could use a normal CH34XX and the browser "kinda understand it" but so far I will switch from IC.

thanx
